fix: deleting tags

diff --git a/.github/workflows/build_deploy.yml b/.github/workflows/build_deploy.yml
--- a/.github/workflows/build_deploy.yml
+++ b/.github/workflows/build_deploy.yml
@@ -157,13 +157,13 @@ jobs:
             ALL_TAGS=\$(docker images \$DOCKER_IMAGE --format "{{.Tag}}" | grep -E '^[0-9]{14}$' | xargs)
             echo "KEEP_TAGS: \$KEEP_TAGS"
             echo "ALL_TAGS: \$ALL_TAGS"
-
-            for tag in \$ALL_TAGS; do
-              if [ -n "\$tag" ] && ! echo "\$KEEP_TAGS" | grep -q "\$tag"; then
-                echo "[INFO] Removing old image tag: \$tag"
-                docker rmi \$DOCKER_IMAGE:\$tag || echo "[WARN] Failed to remove image: \$tag"
-              fi
-            done
+          
+          for tag in $ALL_TAGS; do
+            if [ -n "$tag" ] && ! echo "$KEEP_TAGS" | grep -q "$tag"; then
+              echo "[INFO] Removing old image tag: $tag"
+              docker rmi "${DOCKER_IMAGE}:${tag}" || echo "[WARN] Failed to remove image: $tag"
+            fi
+          done
 
             echo "[INFO] Deployment completed."
           EOF
